# .github/workflows/test-on-pr.yml

name: Test on Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main  

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=app tests/
      - name: Lint with flake8
        run: |
          flake8 app/ tests/


